version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DB_FILE=goods.db
    volumes:
      - ./backend/goods.db:/app/goods.db
    restart: always